# Generated by Django 2.2.24 on 2021-12-29 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_et_prenom', models.CharField(error_messages={'unique': 'Une personne avec ce nom et\\ou prénom existe déjà'}, max_length=200, unique=True)),
                ('sexe', models.CharField(choices=[('masculin', 'Masculin'), ('féminin', 'Féminin')], max_length=15, verbose_name='Sexe')),
                ('telephone', models.PositiveIntegerField(error_messages={'unique': 'Une personne avec ce numéro de télephone existe déjà'}, unique=True)),
                ('date_naissance', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='ajouter une photo', null=True, upload_to='images/profile/%Y/')),
                ('phone', models.PositiveIntegerField(blank=True, error_messages={'unique': 'Une boss avec ce numéro de télephone existe déjà'}, help_text='le numéro de télephone doit avoir 9 chiffres', null=True, unique=True)),
                ('sexe', models.CharField(choices=[('masculin', 'Masculin'), ('féminin', 'Féminin')], max_length=15, verbose_name='Sexe')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
